ssbc/ssb-server

package.json
plugins/friends.js
test/friends.js

modifies the friend plugin functions to optionally take the desired graph
```js
server.friends.all('follow')
server.friends.all() // same as ^
server.friends.all('trust')
server.friends.all('flag')
server.friends.hops(alice, 'follow')
server.friends.hops(alice, 'trust')
server.friends.hops(alice, 'flag')
```
also adds edge-deletion to the graph construction

add trust and flag edges to friend graphs

---

plugins/gossip.js

pretty simple algorithm, updates the peer selection to only choose a peer if `Math.random() < (1 / (1+e.failure))`

added peer backoff on successive failures

---

package.json
plugins/friends.js
plugins/gossip.js
plugins/replicate.js
test/client-auth.js
test/realtime.js

keeps in sync with ssb after https://github.com/ssbc/secure-scuttlebutt/pull/77 change

update sbot to use new ssb object formats {key:, value:}

---

plugins/blobs.js

some additions to help us debug/monitor the blobs exchange
adds logging and the `blob.wants` function, which gives the current jobs queue

Blob tooling (logs, blobs.wants func)

---

config.js
index.js

this was the cause of #83, i was using hostname and the gossip plugin was using host. this PR standardizes the config so this confusion wont occur again

standardized cfg host/hostname to host

---

plugins/blobs.js

there was an error condition where blobs were transferred sometimes but not always. a blob would be "found" on a peer, but then not fetch
turns out the download function had a logical error that would crop up in certain arrangements of data. if the ready `want` list looked like...
```js
[ { id: 'dgkRMPt9u0a9v3I9mrYZkbKbX97LIuSgTLXxa5qsfX8=.blake2s',
waiting: [ [Function] ],
state: 'ready',
has: 
{ 'TNn7v0MsAs8OpQnyRwtsMeROVWGlKnS/ItX966PAWjI=.blake2s': false,
'kIetR4xx26Q2M62vG0tNrptJDFnxP0SexLHaOIkyy08=.blake2s': true } } ]
```
the download wouldnt happen. the `TNn7v0M...` peer was getting selected to download from because it was the first active peer, even though it was marked as not having the file. the download function would select `TNn7v0M`, see the file wasnt there, then abort

fix: blobs now consistently download when discovered on a peer

---

package.json
plugins/gossip.js

new rpc function in the gossip plugin lets us trigger syncs manually, eg from phoenix's address page
decided to implement it, for now, such that it only connects to known peers. however, we could improve it to allow previously-unknown peers if we feel that's useful

added gossip.connect rpc method

---

index.js
package.json
plugins/blobs.js

This change was necessary to make my dynamic-manifest pull request to phoenix.
The main upside of this change is it enables more than one plugin to add http handlers,
Also, it serves the manifest (as either json or js) and the blobs plugin hosts hosts blobs.
Ultimately, this means that the manifest only needs to be maintained in one place.

manage plugin http use with connect.

---

index.js

this emits an "unauthorized" event, but, since ssb-client now cb() silently, it does not dump a confusing error either. Without this, since some plugins expect auth's cb to have arguments, scuttlebot was crashing. This fixes that, and makes ssb-client work.

when ssb-client connects, do not treat it as authed.

---

plugins/blobs.js
plugins/gossip.js

I changed this while investigating the blobs test problem, I don't think this fixed it, but it is better to have configured timeouts instead of hardcoded timeouts.

make all timeouts use configured timeout

---

bin.js
package.json

this adds a special case to the cli tool to use mynqsql-query to parse queries.
it makes it easy to query the data base with a one liner.
for example, get all messages where the first message (after init) is a post
``` bash
sbot query 'sequence=1, content.type=post'
```
will produce a lot of JSON output.

more convienient queries with mynosql-query

---

package.json
plugins/invite.js

Outdated pull-ws-server dep was keeping the auth code from correctly detecting local auth.
Fixing that caused the invites tests to fail, as the test user was correctly authing locally, which didnt have the `invite.use` perms. Fixed that by giving `invite.use` access to the local role.

Fixes for local feeds

---

plugins/blobs.js

fixes a bug in the blobs plugin (shown by the blobs tests) that was introduced when the local role began correctly being recognized

add perms to blobs.has and blobs.get to local role

---

plugins/blobs.js

This PR addresses #175. Changes....
- Each remote is now queried on connect independently of the other remotes (it's no longer part of a oneTrack job queue). If any blobs are found, they are queued for download. When all found are downloaded, the blob's task is released.
- Note, only 20 blobs are queried at once, and so a single connection will download no more than 20 blobs before releasing. (We'll want to enforce this on the serving-end at some point.)
- The download job-queue now allows up to 5 simultaneous downloads, and only waits 300ms before queueing up the next download. This increases the throughput dramatically.

Improve blob sync throughput and correctly release the blobs-task on completion

---

index.js
package.json
plugins/friends.js
plugins/gossip.js
plugins/replicate.js
test/random.js

Adds a crude benchmark and some fixes to make replication faster.
benchmarks of a fullish network (100 users, ~ 1000 messages) to a new user. It's currently taking 1 minute, and about 17 seconds to replicate 1000 messages. including generate 1k messages.
To replicate the receiving client verifies about 400 signatures (if it queues a few messages it just verifies the last one in the current queue).
I also benchmarked some signing libraries (not in this PR though) - eccjs (which we use) can verify 100 signatures in 4 seconds. Slow. To verify 400 signatures would take 14 seconds, which accounts for most of the time to replicate.
I also looked at some other libraries - ecma-nacl is twice as fast (in browser or server). elliptic is way faster on node but slower on the browser (? not sure why …

Tracking PR for replication performance

---

lib/api.js
package.json
plugins/replicate.js
test/random.js

This allows you to track real time replication progress.
when you run `test/random.js` you'll see a simple ascii progress bar, too.
The replication plugin adds a progress observ(able) to the rpc object,
and if you pass it a listener it'll be updated with the current progress.
It is only updated every 100 ms, max.

Replication Progress

---

client.js
test/random.js

Using `hash(address.key)` was causing a bug in `invite.accept()`, as it was following the `rpc.id` and therefore not following the feed id

use key instead of hash(key) as rpc.id

---

plugins/friends.js
test/friends.js

This is to support the change to a `flag` attribute in `type: contact` messages.

replace trust-graph with flag-graph in friends

---

plugins/gossip.js

this is a refactor of the gossip plugin. code was deduplicated, and concerns separated.
for example, there was `connect` which chose a peer to connect to, and then called `connectTo` which actually connected to it. refactored so to have a choosePeer function and then a connect function.
I want to take this towards separating the strict parts which can be easily tested (adding a peer, etc)
from the fuzzy parts (choosing which peer to connect to, etc)
I think we do a similar thing with blobs.

tidy/refactor: clean up gossip controls

---

plugins/replicate.js

fix: replicate plugin now returns api during init, as intended

---

plugins/gossip.js

This was causing peers in the sync page to appear to be connecting, when, in reality, the connection attempt had failed

update peer-state and log when gossip connections fail

---

api.md
index.js
plugins/block.js
plugins/friends.js
plugins/friends.md
plugins/replicate.js
test/friends.js
test/random.js

This applies a simple algorithm to ensuring that peers do not publish too much at once.
peers accept anything from someone they follow, but only 100 items (default) per day from indirect peers.
this depends on some small breaking changes to secure-scuttlebutt

replication back pressure

---

bin.js
package.json

This change means the `sbot` client doesn't load the entire scuttlebot dep tree, making loads faster.
Also, it gets the client manifest from the file (which previous version actually didn't do)
That is helpful for development because you can test a new plugin in scuttlebot/patchwork and hit it directly via the `sbot` command.

lighter more flexible client

---

plugins/blobs.md

The documentation for the `blobs` plugin commands `add` and `rm` is a bit mixed up.

Fix blobs plugin documentation mixup (add & rm).

---

bin.js
plugins/gossip.js
plugins/invite.js
plugins/logging.js
plugins/replicate.js

This PR makes a bunch of updates to quite down the logs, significantly.
1. The replication success-report now just tells you how many feeds were updated, and how many new messages there were. If there were no new messages, then nothing is output.
2. All log entries now include the ID of the remote. It previously used `._sessid`, which I think is old code because I dont see any references for it anymore.
3. Connection errors no longer include a stack trace.
4. Added a new log level, 'notice', which is between 'info' and 'warn'. So the full list, in order of most verbose to least, is: info, notice, warn, error.
5. Moved the replication summary to 'notice', and left all other info logging where it was.
5. Added `logging.level` config, which lets you set the verboseness. It defaults to …

Nicer logging

---

plugins/blobs/queue.js
plugins/blobs/replication.js
test/blobs-quota.js

It was a really stupid error, had two things named `delay` so it was causing `setTimeout(fn, NaN)` (probably) anyway, cpu levels are now acceptable.

fix CPU spin out on over quota

---

lib/util.js
plugins/invite.js
test/invite.js

This patch updates scuttlebot to correctly parse addresses with IPv6 hostnames, as in
https://github.com/ssbc/ssb-ref/commit/3e68d06149e19847e8bcb6ea8975c9227ca555c5 and
https://github.com/ssbc/ssb-ref/commit/8d5f7c3badc8e5fc48090e384d8fa5458619a0f7

Handle IPv6 addresses

---

plugins/gossip.js
plugins/replicate.js

This _should_ replicate strangers you find on the local network, but only the their first 100 messages (by currently hardcoded quotas - easy to change) also it should replicate their avatars.
@mixmix you are more likely to have two computers running pw next to each other, can you test this?

replicate peers on the local network, even if they are strangers

---

lib/validators.js

`.add()` was incorrectly always expecting `.previous`. This makes it optional.

fix validation: .previous is optional in messages (add())

---

plugins/blobs/replication.js
plugins/replicate.js

quotas wasn't working well, and, I suspect that calculating the path to the sharer in the blobs quotas system might be what is causing the spinning cpu.
``` 
ssb_party=1 ./bin.js server
```
or edit config. otherwise this is backwards compatible, so we can merge this into patchwork and let people who where having problems test it an see if it improves.

disable all quotas by setting party mode

---

plugins/invite.js

Invite codes are outputted with quotes around them, so sometimes they get shared that way. I had somebody get tripped up by this, so automatically stripping the quotes is probably a good idea.

if an invite code is surrounded in quotes, automatically remove them

---

bin.js

Commit 11f01217 (oops, fix so you can actually start the server when not
using --, 2016-05-15) broke the change from commit 0f96771a (separate
argv by -- and use later part for configuration., 2016-05-14).
Fix this by adding back the i part of the argv.slice.
Signed-off-by: Johannes Löthberg <johannes@kyriasis.com>

Fix 11f01217 to make 0f96771a work again

---

bin.js

Once upon a time this was possible but it got trampled somewhere.
This enables you to set a `master` configuration on your pub, and command your pubserver to accept commands from your local client, which has better latency than sshing onto the server and then running local commands.

set remote key via host, to be client to another sbot

---

plugins/friends.js

As posted in the #scuttlebot channel on patchwork:
> I accidently followed a message (instead of a feed) by copy/pasting the wrong id into sbot publish. It completely broke replication for my local instance. No errors, just replication never finishes. Didn't seem to affect the outside world, but not 100% sure about that yet.
>Even publishing an unfollow didn't fix it. The only way for me to avoid scrapping this feed is to manually filter out non-feed ids from the friends list. Maybe this should be in scuttlebot by default?
@dominictarr This is probably a bug, really scuttlebot should not be able to treat non-feeds as friends. 
**This PR enforces that all `follows` specified by `contact` posts are `feeds`, and will ignore other types of messages.**

plugins/friends: only allow feeds as friends (not messages)

---

bin.js

before, the ` "caps": {"shs": "...." } ` in `.ssb/config` wouldn't get passed to `sbot` client calls, like `whoami`.
(re %sRD2wfvldRwi95yqTTN5SRnmoG0c1ktcXFSUF8lQlh8=.sha256)

pass caps from config to ssb-client

---

.travis.yml
plugins/gossip.md
plugins/gossip/index.js
plugins/local.js

Currently if sbot discovers a local peer, it will keep it in the peer table forever, even if that local peer goes offline or you change networks. This has a few problems (including sbot trying to connect to missing peers), but also makes it hard to easily access a list of local peers. 
**This PR adds an automatic cleanup to `local` that will remove peers from the `gossip` table that haven't broadcasted in over 10 seconds.**
With this PR in place, `patchwork-next` will no longer have to override the gossip and local modules and will be able to work properly on top of a standard sbot server.
cc @ahdinosaur @dominictarr @mixmix

automatically remove old local peers from peer table

---

plugins/replicate.js

Finally tracked this thing down! 🎉 
There is a typo in `plugins/replicate.js` that uses `opts.sequence` instead of  `opts.sequence || opts.seq` causing realtime push to break.
This is most commonly noticeable when connected to someone on the local network and you don't see their posts until after they restart, but I suspect this has been breaking persistent gossip for ages!
cc @dominictarr @mixmix @ahdinosaur @clehner

fix realtime replication push

---

plugins/gossip/index.js
plugins/replicate.js

as discussed in [%SMqHQTSeyR8Zq0KcSe2z0HbvjW1CqKIlJ1leuVVL4G0=.sha256](https://viewer.scuttlebot.io/%25SMqHQTSeyR8Zq0KcSe2z0HbvjW1CqKIlJ1leuVVL4G0%3D.sha256):
- log a stream error only if it is not one of the expected benign errors, and then only log it once instead of logging it for each substream.
also, pre-emptively close legacy erroring substreams, to save bandwidth (analysis in [%368B7blWHcWTEzqGO4DDipDBCLwvRlKxwVxTOFtV9kY=.sha256](https://viewer.scuttlebot.io/%25368B7blWHcWTEzqGO4DDipDBCLwvRlKxwVxTOFtV9kY%3D.sha256)
and also, show Connected/Disconnect on the log for peers that are not in the peer table (e.g. incoming non-pub connections)

Improve replication error handling

---

package.json
plugins/friends.js
plugins/replicate.js
test/random.js

As per ssbc/patchwork#447, this PR removes patchwork's need to be running a forked sbot version.
I was going to remove the old `progress` but it turns out some tests need it to pass, so I left it in. I have also left the old `total` value in. This is kind of broken because `total - progress` usually never quite makes it to `0`, but it is better than it used to be (there was an off by 1 error in the old code).
The old `feeds` was broken since adding persistent gossip. From the code, it looked like it was supposed to count the number of feeds currently syncing, but since they never stopped, it didn't decrement until the peer disconnected. Seemed a little silly to me. **So I've changed it to now be the total number of feeds we know about**.
It gives us the total number of feeds that …

port patchwork style progress to scuttlebot

---

plugins/replicate.js

Just noticed that sometimes (particularly right now with the high load on pubs) the "downloading messages" progress stalls and never completes. The only way to make the progress bar go away is to restart.
Turns out it is a display only issue. This PR correctly handles cleanup when a pub disconnects before sync completes.

fix progress stalling when pubs disconnect before completion

---

plugins/replicate.js

Continuing from #383. Here's an alternative strategy that uses what we know about the peer already to decide when to mark as sync. It also falls back to a timeout after 3 seconds of no message received. 
Does this look okay? @dominictarr @clehner @ahdinosaur

replicate: reduce bandwidth by replacing double stream with peerHas check

---

plugins/gossip/index.js

https://github.com/ssbc/scuttlebot/commit/ac51d55eb952fb66353ffa811b94522fee651e1a#commitcomment-21850365
Probably not supposed to be here, right?

remove (unintended?) console.log from gossip

---

package.json

Current scuttlebot depends on ssb-ref `^2.6.2`, which for some people due to semver might be installed as 2.6.**3**. Version 2.6.3 is pooped because it [broke support for IPv4](https://github.com/ssbc/ssb-ref/issues/10). I suspect some people might be getting problems with this.

Use ssb-ref 2.7.1 which works for IPv4 and IPv6

---

plugins/plugins.js

- Skip loading a plugin with an already-used name,
as mentioned in https://github.com/ssbc/scuttlebot/pull/407#issuecomment-305742813
- Add back plugin loading error checking removed in 5653a26d6cfcd9a9cff414d2c291fc24e7a294aa
This addresses https://github.com/ssbc/scuttlebot/pull/407#issuecomment-305731499 so that a user upgrading to the flume branch will not get crashes if they have previously configured user-plugins which are now loaded by scuttlebot core. (these being ssb-ws, ssb-query and ssb-links) - instead, they will get a one-line error message for each, saying that the plugin is already loaded.
I also reenabled wrapping loading the plugins in a try-catch block and checking that the plugin object is valid with assertSbotPlugin, for robustness.

Improve robustness of loading user-plugins

---

package.json

After installing 10.0.0, the bin-script went empty on me:
```shellsession
npm i -g scuttlebot
cat $(which sbot)
```
Turns out the `bin` script path in `package.json` is off.  From the looks of it, `sbot.js` was renamed to `cli.js` without a corresponding `package.json` change?  I've done that more times than I care to count.
Here is the corresponding `package.json` change.
Thanks to all!

Fix npm bin-script path

---

plugins/replicate/legacy.js

This PR removes old `loadedFriends` check that doesn't work with flume and breaks feed sync progress
This is currently stopping sync progress from working in Pathwork

remove old `loadedFriends` check that doesn't work with flume

---

index.js
plugins/gossip/schedule.js

see [%/+J9b8I4bDkw+myccUxGzpj28vyZ78TTkeBCdVWB26w=.sha256](https://viewer.scuttlebot.io/%25%2F%2BJ9b8I4bDkw%2BmyccUxGzpj28vyZ78TTkeBCdVWB26w%3D.sha256)
> ## Overloaded Scuttlebot
> 
> The other issue only affected users who were on the same wifi. Turns out scuttlebot still tries to connect to local peers before the migration has completed. This causes it to try and replicate all the data at the same time as upgrading it, making everything freak out and go bad.
>
> We couldn't get it to work properly until wifi was turned off.
>
> We need suspend gossip while the migration is taking place.
Then @dominictarr replied:
> There is a db.ready observable that is set to false while migration is incomplete. Gossip can check that.

don't attempt to connect to peers while migration is running

---

lib/has-network-debounced.js
plugins/gossip/schedule.js

I have been trying to figure out why Patchwork runs so badly on my girlfriend's computer. It's an old thinkpad from 2011 running Windows 8. Finally hit a breakthrough in the profiler:
Each connection attempt is blocking for more than 2 seconds!! Tracked this down to many calls to `hasNetwork`. It was being called 100s of times a second. And apparently it is a slow blocking command on this machine. Haven't investigated why it is so slow, instead I fixed it the quick and dirty way.
**This PR adds a 1 second debounce to all `hasNetwork` requests. And suddenly everything  runs beautifully on that machine.**
cc @dominictarr

gossip: debounce has-network for better windows performance

---

plugins/gossip/index.js
plugins/replicate/legacy.js

Noticed that while adding the `db.ready` check on gossip scheduling solved most of the _replicate while migrating_ bugs, other machines can still connect to you, and you'll try to replicate with them.
**This PR adds some more `db.ready` checks on replication. Will immediately disconnect from a peer if it tries to connect in this time.** It also adds a missing `notify()` case for removed local peers.
Issue in patchwork: ssbc/patchwork#567
cc @dominictarr

fix db.ready check for local peers

---

plugins/plugins.js

Don't attempt to access a property on a plugin that has returned `undefined`.
Why this was a problem for me:
```
$ sbot plugins.install blob
$ sbot server
/home/.nvm/versions/node/v6.11.3/lib/node_modules/scuttlebot/plugins/plugins.js:187
throw new Error('plugin at:'+module_name+' expected name:'+name+' but had:'+plugin.name)
^
TypeError: Cannot read property 'name' of undefined
at Object.module.exports.loadUserPlugins (/home/.nvm/versions/node/v6.11.3/lib/node_modules/scuttlebot/plugins/plugins.js:187:91)
at Object.<anonymous> (/home/.nvm/versions/node/v6.11.3/lib/node_modules/scuttlebot/bin.js:54:32)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load …
```

Immediately stop loading plugin if it is falsey

---

plugins/replicate/legacy.js

The `toSend[id] == null` is an old check that is unnecessary after adding the `e.source === 'local'`. It stops replication from requesting feeds from a local peer after restart if you have not followed them, which is really not what you want.
**This PR removes that broken check, and now local peers replicate their own feed as expected!**
Gonna roll this out in the new version of patchwork about to be released.
fixes #437

fix updating from local peers that you don't follow

---

package-lock.json

It looks like this has fallen quite a bit behind, so it's hard to tell which packages should _actually_ be getting installed to get everything working. _Keeping_ this file up-to-date will depend on future PRs, but this is a one-time fix to bring us up-to-date.

Bring package-lock.json up-to-date

---

plugins/invite.js

Tested this together with https://github.com/ssbc/ssb-ref/pull/13 and it makes accepting invites over tor work again.

Make invite.accept work with onion

---

plugins/gossip/index.js

Use `server.emit('log:info', ['SBOT', xyz, 'Xxz'])`, rather than `console.log('Xxz', xyz)` for the gossip plugin's sometimes chatty information updates.

Emit gossip log messages rather than logging to console

---

plugins/gossip/schedule.js
plugins/replicate/legacy.js

The current PR contains a quick hack to prevent gossip from being scheduled while feed download is taking place. It detects this by checking to see if a message was downloaded in the last 500ms.
Currently it uses a nasty global whacked on the `sbot` to share the state out of legacy replication into gossip scheduling.
---
But the important thing is just how much this improves onboarding performance. It no longer crashes! Completes in a few minutes instead of mysterious indefinite locking.
See https://github.com/ssbc/patchwork/issues/631 for more context.
cc @dominictarr @clehner @ahdinosaur

prevent gossip scheduling while downloading messages

---

.travis.yml
test/invite.js

I've noticed that the Travis CI builds seem to be broken by the fact that [Travis doesn't support IPv6](https://docs.travis-ci.com/user/reference/precise/#Networking). This PR does three things:
- Disable IPv6 under Travis CI, emitting a simple warning instead
- Replace Node.js 6.9.5 test with Node.js 6.x for maintenance LTS testing
- Add Node.js 8 test with Node.js 8.x for active LTS testing
Please let me know if this could be done better, I'm open to any input. Thanks!
Resolves #447 
---
Note: it's still [possible](https://travis-ci.org/ssbc/scuttlebot/jobs/376165375) to fail, probably due to a race condition, but at least those jobs can be re-triggered with a reasonable probability of passing the next time. The goal of this PR is to make testing better, not perfect. :upside_down_face:

Fix Travis CI

---

package-lock.json
package.json

This is needed to bring scuttlebot up to speed with other applications in the the system in terms of vesion of index it's using for ssb-query. (I think this is only relevant for the `sbot server` command?)

bump ssb-query to 2.1.0

---

index.js
lib/ssb-cap.js
plugins/plugins.js

I've been seeing this deprecation notice for a while and wanted to resolve it:
> [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Background: [Porting to the Buffer.from()/Buffer.alloc() API](https://nodejs.org/en/docs/guides/buffer-constructor-deprecation/#variant-1)

Replace deprecated buffer constructors with `Buffer.from()`

---

plugins/gossip/index.js
plugins/gossip/init.js
plugins/local.js
test/gossip.js

I want gossip to use multiserver addresses locally, so that you can for example, gossip over websockets, or webrtc, or [tunnel](https://github.com/dominictarr/ssb-tunnel) to a peer. The code is still ugly, but I just fixed up the minimum amount to get this in.
Also I added an option to disable replication to `pub` advertisements. These were an ugly hack that we made back in the day, that I'd like to remove. (switching to user invites should achieve that) in particular, they are a problem because it's hard to tell if a pub is really still at that address - and since you announce someone else's address, which is insufficiently consentful.

gossip uses multiserver addresses locally

---

bin.js
index.js
package.json
plugins/no-auth.js
plugins/onion.js
plugins/unix-socket.js

I started out just wanting to get the old ssb-ws plugin updated, and working with sbot again, but in 12 sbot added it's own ws server, so I needed to move that... and then I also thought that those other plugins should be moved away.
I'm seriously thinking that secret-stack shouldn't even load a networking plugin (or shs) and that should be loaded by sbot user...
I've also been thinking that now that it's so easy to add more protocols, and they are well-integrated, we need a good way to add protocols to ssb-client... it would be nice if ssb-client also had a `.use(plugin)` method - but it just didn't create a server? something like this is probably important to get ssb on the browser

refactor networking plugins, don't use by default, and use ssb-ws instead of inlined ws plugin

---

package.json
test/bin.js

Add test for sbot getAddress 
sbot should provide a multiserver address containing ws: by default
Also bumps ssb-config dependency to 2.3.6, which will make the test pass.
NOTE: this PR also contains the two commits from my previous PR, so either just merge this one and close the other one, or merge the other one first, then this. You also need to publish ssb-config 2.3.6, there's a PR in ssb-config too.

Test for bin.js

---

.npmrc

Resolves #534 
I've pushed an `add-npmrc` branch for *every* SSBC repo that follows the "no package-lock.json" tendency -- should I open pull requests for each of them, or should I just merge to `master` and push? I've done the same with `add-gitignore` for NPM package repos that don't have `node_modules` being ignored by git.

Add .npmrc to disable package-lock.json

---

.gitignore
package.json
plugins/invite.js
plugins/local.js
test/bin.js
test/invite.js

mainly this is updating the invite plugin, so that if allowPrivate is used, it uses the local scope instead of public.
depends on: 
* https://github.com/ssbc/multiserver/pull/32
* https://github.com/ssbc/ssb-config/pull/25
* https://github.com/ssbc/secret-stack/pull/31
* and ssb-ws@3.0.2 @regular I couldn't quite figure out what was going on with the multiple servers thing on ssb-ws@4
all the tests are now passing again, and `getAddress <scope>` returns something sensible.

support multiple scopes

---

bin.js
package.json

I was looking at the various flume indexes and bumped into the links and links2. While links is used internally by secure-scuttlebutt for things like messagesByType, links2 doesn't really seem to be used at all. Maybe it was used for some of the old functions that was removed once?
Doing a full search on github reveals that it is exposed in ssb-ws [here](https://github.com/ssbc/ssb-ws/blob/master/index.js#L28) and used in patchfoo. But patchfoo installs it as a plugin, so that shouldn't be any problem. I then checked mvd at it appears only to be referenced in [manifest](https://github.com/evbogue/mvd/blob/392e50fcc67f4ad4b873fc95b096e3018404f255/manifest.json#L70) but never used. @evbogue can you confirm?
Ping @regular are you using that api for anything?
The thing is that this index was …

Remove ssb-links

---

plugins/plugins.js

The problem is that earlier if one had invalid json it would just end up with an empty dict and write the plugin to that, thus nuking your carefully handwritten config. This bails instead and actually shows what is "wrong" with the file.

Don't nuke config if its not valid json.

---

plugins/plugins.js

This was recently refactored to prevent the server from overwriting invalid config files, but had a bug where it would crash when the config file was missing. This commit aims to be the best of both worlds, where we can continue safely on missing config files but crash loudly when the config file has the wrong permissions or is invalid JSON.
Resolves #584

Fix config file read

---

plugins/logging.js

sbot would ignore the logging level when it was set to "error" because its index was tested for falsiness. Now we separate testing for the existence of a config log level and getting its `LOG_LEVELS` index.

Fix logging for level 'error'

---

plugins/gossip/init.js

It is currently not possible to control which peers get added to the gossip table because this is generated deep inside the gossip plugin.
**This PR adds the config option `gossip.autoPopulate` that when set to false, prevents the peer table from automatically being populated from `{type: 'pub'}` messages, allowing the instance to manually populate however they want.**
An example of where this is needed is if you want to exclude adding blocked pubs to the peer table.

add config.gossip.autoPopulate to allow disable of auto build of peer table

---

bin.js
package.json

This PR adds `ssb-ooo` to the default plugin list. Now we can have out of order message support on all the pubs (assuming they update).
closes #600 
---
I am having trouble running the tests on macOS (test/invite.js is failing because the codes are being generated as external ipv6 address for some reason). Can @ahdinosaur do the honours of merging and pushing out a new release? (or anyone else for that matter!)

add ssb-ooo as default plugin

---

plugins/gossip/schedule.js

This plays well with [ssb-friend-pub](https://github.com/ssbc/ssb-friend-pub) module. 
I reused the "friends" type for adding these peers so that friend-pub also should work together with the global module and prioritize friends.
The idea with this flag is that one should be able to only connect to peers marked as friends.

Add friends config option to connect to peers marked as friends

---

api.html
index.html

scuttlebot has migrated to ssb-server, links in the docs website broke. This should fix some of them.
/docs/scuttlebot pages are unaffected

ssbc.github.io scuttlebot links fix

---

README.md

I recently tried to modifying how I start my `ssb-server` and I couldn't find how or where to learn about configuration.
This PR adds:
- a clear link out to `ssb-config` (where the config you need to know about is to start the server!)
- clear link to other modules / docs
- a complete `example use` code snippet
- the prior example was junk <3
---
_I had a bunch of kinda wound up feelings writing this. I imagined a new dev arriving at this README and just feeling stupid. I felt stupid and I'm an "experienced" dev in this system. So please, in reading this, it might not be perfect but lets make some improvement that throws people a bone (idiom which means help people just a little bit)_

add a useable example

---

.npmrc
npm-shrinkwrap.json
package.json
test/deps.sh

@christianbundy I propose we fix it this way.
* `npm ls` is part of tests, with `--package-lock` enabled in case package-lock is disabled, this makes npm respect `npm-shrinkwrap.json`, yes.
* `ssb-server` (or other distributions) are currectly expected to include dev deps on things they are running in `test/deps.sh`. We could have a script to update this, but I think it's okay for now.

Fix shrinkwrap

---

npm-shrinkwrap.json
package.json
scripts/pretest.js
test/deps.sh

@dominictarr 
If we're going to do it then we may as well automate it. Here's a first stab that runs before `npm test`:
1. Collect the list of dependencies from ssb-server's `package.json`
2. Collect the list of dependencies from each plugin
3. If a plugin devDependency is incompatible with ssb-server or another plugin, throw an error
4. If we have new devDependencies to install, install and exit 1 (to ensure bad commits don't pass test)
I think this is better than my previous suggestion of `npm install` because it was running after `npm ci` and messing with our determinism.
Resolves #625

Add pretest

---

README.md

Updating the README js example to match the changes made in https://github.com/ssbc/ssb-server/pull/610 where gossip and replicate were moved out to their own plugins.

Update README example to reflect new refactoring

---

README.md

The documentation states the use of `ssb-server/plugins/master` something that was broken out of ssb-server some time ago. This small fix here makes sure others don't trip over the same mistake I made ;)
Under the hood there's actually a significant difference between the commands 
`ssb-server start` and the JS example. It's perhaps not a bad idea to at least reference https://github.com/ssbc/ssb-server/blob/607808d37d75f92002c25bd80aa28fea9052479a/bin.js#L45-L62
(which is a nice list of plugins to get started with given one only takes what one needs).

Require ssb-master instead of non-existing plugin

---

npm-shrinkwrap.json
package.json

Addresses the bug mentioned in `%zGIBPSlxKA1mPj8r7wJ7u9GjNKw1AD/q3BHdKQ3V7IY=.sha256`, where a bug in `ssb-blobs@1.2.1` affects patchfoo use.

upgrade ssb-blobs to 1.2.2

---

README.md

I separated example usage docs into two headers: 
and
because I find it confusing when they're mixed. Then, each has a Bash, and JS section. This helps clarify a lot of things.

Improve README organization and links

---

.travis.yml
npm-shrinkwrap.json
package.json
test/bin.js
test/caps.js

See the commits for more details.
TL;DR:
- Replace `getAddress()` with `address()` when call is happening over MuxRPC.
- Since our dependencies don't support Node.js 6, change Travis config to test 8 - 14.

Replace `getAddress()` with `address()`

---

.travis.yml
bin.js
index.js
npm-shrinkwrap.json
package.json
test/bin.js

with the upcoming `ssb-db@20` we're removing the classic private-box functionality by default.
To preserve the behaviour state of `ssb-server`, this adds it back into this distro.
**NOTE : this needs `ssb-db` to be upgraded (once that's published) before merging**

add ssb-private1

---

README.md

Fixes #728 - Changed external property in config example. The previous example used an array and led to issues creating invites on the first setup for newbies. The multiserver net plugin seems to call `replace()` on the external property, which does not work for arrays.

Updated config example in README

---

index.js

Problem: The SSB-Server configures `caps` as a buffer, which breaks all
connections because it's supposed to be a base64 string.
Solution: Use the base64 string just like we're doing in SSB-Config.

Fix caps being interpreted as a Buffer
