plugins/friends.js

added opts to friends.hopts()

---

plugins/invite.js
test/invite.js

closes https://github.com/ssbc/scuttlebot/issues/72
decided to make 'already followed' an error condition so that the client could reason about it

invite code fixes

---

config.js
index.js
package.json

per https://github.com/ssbc/scuttlebot/issues/63

added phoenix as the default frontend

---

plugins/gossip.js

fix: sameHost now compares ports of both hosts

---

plugins/blobs.js

two crash-fixes for the blobs plugin

more blob fixes

---

plugins/gossip.js

https://github.com/ssbc/scuttlebot/commit/b6c7d6fe1246fda5d16ccde8412bb286f060878e fixes https://github.com/ssbc/scuttlebot/issues/93 for sure, and i think should fix https://github.com/ssbc/scuttlebot/issues/94 too

gossip plugin bugfixes

---

bin.js

`bin.js` was timing out when i attempted to connect to it. this seemed to solve it.

bin.js now correctly connects to localhost

---

README.md
lib/manifest.js

allows for https://github.com/ssbc/phoenix/pull/307#issuecomment-72983684

add relatedMessages to manifest

---

README.md

Closes https://github.com/ssbc/scuttlebot/issues/60
This was already implemented, but was not documented.

document remote master

---

lib/api.js

This adds logging for the add command... to investigate https://github.com/ssbc/phoenix/issues/299#issuecomment-73157664
it's not happening because other adds are getting in the way, but and it's happening in scuttlebot, so it's not phoenix.

logging for add command

---

bin.js

this reverts https://github.com/ssbc/scuttlebot/pull/102
and should resolve the problem but depends on https://github.com/ssbc/ssb-config/pull/4

use config directly in client

---

plugins/blobs.js

Addresses point 2 in https://github.com/ssbc/scuttlebot/issues/116

only emit wanted blob once

---

index.js
lib/api.js

https://github.com/ssbc/phoenix/issues/319

Use permissions given to createAccessKey in rpc auth

---

bin.js
index.js
package.json

fixes https://github.com/ssbc/scuttlebot/issues/150
the problem was: https://github.com/ssbc/scuttlebot/issues/150#issuecomment-89483263

do not write manifest until plugins are loaded

---

README.md

Fixes README to use 'publish' in examples rather than 'add'

---

package.json

this updates to the lastest of everything i think,
since it updates ssb-msg-schemas I think thats a breaking change?

update all deps

---

README.md
index.js
lib/manifest.js
lib/util.js
package.json
plugins/blobs.js
plugins/gossip.js
test/master.js
test/realtime.js

this combines https://github.com/ssbc/scuttlebot/pull/158 https://github.com/ssbc/scuttlebot/pull/142 and https://github.com/ssbc/scuttlebot/pull/118
tests pass. I think this should be a breaking change because of https://github.com/ssbc/scuttlebot/pull/158 (breaking change in ssb-msg-schemas)

consolidate current prs into one pr

---

plugins/friends.js

fixes https://github.com/ssbc/scuttlebot/issues/138
@dominictarr if you'd prefer to keep using level-memview, I can move this fix into that repo. This code is pretty compact, though.

fix friends graph creation (use .sync event)

---

plugins/gossip.js

Per #176, makes gossip prefer pubs with many unique announcements

Gossip with popular pubs

---

plugins/blobs.js
test/blobs.js

Prioritizing blobs by recency, user interest, and failure-to-fetch

Blob prioritization by requests, age, and failure rates

---

package.json
plugins/gossip.js
plugins/replicate.js
test/server.js

These changes will make it possible to implement the "initial sync" ui, and a general network-sync UI, in phoenix.

Updates to support a sync-progress UI in phoenix

---

README.md

links to docs, and remove gitter, because we don't actually use it.

link to ssb-docs

---

package.json
plugins/blobs.js
test/blobs.js
test/blobs2.js
test/blobs3.js
test/realtime.js
test/server.js

get everything working with Sha256

---

package.json

rimraf needed for global install

---

index.js
package.json
plugins/gossip.js
plugins/invite.js
plugins/replicate.js
test/invite.js
test/random.js
test/server.js

made these changes to get it working with patchwork.
the most important change was to progress bars.
now a progress message looks like this:
``` js
{type: 'progress', peerid: <id>, progress: p, total: t, feeds: f, sync: bool}
```
where `feeds` is the number of mutual feeds you are replicating, and `sync` is whether you are already in sync.

various bug fix, and improve progress bars

---

.gitignore
bin.js
package.json
plugins/local.js

just fixing a few small bugs in the CLI
and adding local peer detection, via udp multicast

fix some cli bugs + local peer detection

---

plugins/gossip.js

This fixes the network sync page error I was seeing

set peer.connected to false on closed event

---

plugins/block.js
plugins/invite.js

fixes
https://github.com/ssbc/scuttlebot/issues/236
and
https://github.com/ssbc/scuttlebot/issues/235
as discussed in those issues.
this is just a patch.

fix some small bugs.

---

api.md

Makes it accessible from the CLI and RPc

Add getAddress to api.md

---

plugins/gossip.js

fix: decrease count of open connections in gossip on failed connect

---

.travis.yml

Doing this until sodium builds on more recent nodes

update .travis.yml to only build on node 2.5

---

package.json
plugins/gossip.js

trigger gossip syncs when the device wakes up from sleep

---

plugins/gossip.js

This detects if you have a network interface, and doesn't try to connect to peers that you won't be able to reach.
I'm starting to think it's time to work on gossip strategies again. I looked at this a while back, but decided that it wasn't worthwhile because there was only my pub, but now several people are running pubs.
This is on top of the blobs refactor which I think we'll merge this week.

don't try to connect to remote server without wifi.

---

package.json

Fixes https://github.com/ssbc/scuttlebot/issues/274

package.json - move pull-paramap from devdeps to normal deps

---

plugins/invite.js

Closes https://github.com/ssbc/scuttlebot/issues/269

Fix the nefarious mystery error log

---

plugins/replicate.js
test/blobs.js
test/blobs2.js
test/server.js

this fixes a test breakage introduced by https://github.com/ssbc/scuttlebot/pull/285

Logging fix

---

bin.js

@dominictarr we discussed this previously. This will make `sbot blobs.add` output the hash of the added file.

hack: override blobs.add CLI call, in bin.js, to get the hash output

---

package.json

Closes %kgesKEERrciXlb0CLdaTrB03ZlrO/eM3UvszzbrzLqY=.sha256

Bumped is-valid-domain to 0.0.2

---

test/invite.js
test/random.js

These extend test timeouts so that they can pass on slow computers, like a raspi2.  They were failing before.
```
bret-raspi:scuttlebot bret$ node test/random.js 
TAP version 13
generate NAMES
replicate GRAPH
CONNECTION 1453686592034 0
************************************************** 418/418:21ok 1 counter is as expected
ok 2 should be equal
ok 3 (unnamed assert)
ok 4 last.total
ok 5 last.total
DONE 11.592 1 36.05935127674258
.................................................. 0/0:218:21
1..5
bret-raspi:scuttlebot bret$ node test/invite.js 
TAP version 13
[ '192.168.1.110:14064:@JVjVTqICYEs+xgIBd/oNPQLY5kOqh4CW5fWyyy4jm/o=.ed25519',
'hOXGH0fpiqVq6JNO9RYqgGbnT9Qaa4HPoN3+DKhMV74=' ]
ok 1 should be equivalent
done
ok 2 alice follows bob
{ …
```

Extend timeouts for slower systems

---

README.md

minor change on the example,  

---

bin.js
create.js
index.js
plugins/blobs/index.js
plugins/blobs/queue.js
plugins/blobs/quota.js
plugins/blobs/replication.js
plugins/friends.js
plugins/invite.js
plugins/local.js
plugins/logging.js
plugins/master.js
plugins/replicate.js

Adds commenting and removes some dead code

Add comments, do minor cleanup

---

package.json
plugins/gossip.md
plugins/gossip/index.js
plugins/gossip/schedule.js

This should fix https://github.com/ssbc/scuttlebot/issues/349
gonna test suspend while I got get a bite. then merge if this works.

reconnect after change network or suspend

---

README.md

Signed-off-by: Kenneth Lim <kennethlimcp@gmail.com>

syncronization --> synchronization

---

api.md
lib/validators.js

Added .limit, .keys, and .values opts, which had been missed

update createHistoryStream docs and validator

---

plugins/replicate.js

taken from https://github.com/ssbc/patchwork/commit/0b9adb1dfcfd2248f55f9dc2130f2d53aeb91794
@mmckegg and i have no idea _exactly_ why an error happens without this, only that it _somehow_ _sometimes_ fixes _something_. yikes. :sweat_smile:

fix bug replicating with local peers

---

plugins/gossip/index.js
plugins/gossip/schedule.js

@pietgeursen needed this, so I cherry-picked it from the flume branch.

enable configuring no gossip, or connect to seeds only

---

plugins/invite.js
plugins/invite.md
test/invite.js

%UcqW5DcDjD8U9PbYxTnCz9Zl+7HoUTf8usOnRA4uuOA=.sha256

Allow setting a note for an invite code

---

plugins/gossip.md
plugins/gossip/index.js
plugins/local.js

%B7Z0Y+y5wQiiXATzQPi9TI6YKm2F+hnbTfufT5tgayk=.sha256

Add gossip.enable, gossip.disable functions

---

api.md
index.js
plugins/gossip/index.js
plugins/local.js
plugins/replicate/legacy.js

The idea here is to have a callable method that just tells you what the hell is going on.
I.e. just show some stats as described in `%bNUMWkvfMXbrvmNX4phO4XD5RaCFKPSZRjjJy6fkKOY=.sha256`
here is what my current output looks like:
```
{
"sync": {
"since": 113210607,
"plugins": {
"last": 113210607,
"keys": 113210607,
"clock": 113210607,
"feed": 113210607,
"time": 113210607,
"friends": 113210607,
"query": 113210607,
"links2": 113210607,
"contacts": 113210607,
"about": 113210607,
"backlinks-EMovhfIrF": 113210607
},
"sync": true
},
"gossip": {
"@5XaVcAJ5DklwuuIkjGz4lwm2rOnMHHovhNg7BFFnyJ8=.ed25519": {
"host": "104.236.22.57",
"port": 8008,
"key": "@5XaVcAJ5DklwuuIkjGz4lwm2rOnMHHovhNg7BFFnyJ8=.ed25519",
"source": "seed",
"announcers": 18,
"duration": {
"mean": 5618.666666666667,
"stdev": …
```

implement a status() method

---

README.md
bin.js
plugins/gossip/index.js
plugins/gossip/schedule.js
plugins/logging.js

A stumbling block for me when trying sbot for the first time is knowing what (if anything) is going on with the server. These changes add config status and peer connect/disconnect/info messages at the 'info' logging level, and adds a README note to suggest starting with level info.

sbot server --logging.level=info output

---

index.js
package-lock.json
test/createMultipleServers.js

I need the ability to create multiple sbots, especially for testing.
This doesn't break the existing api. Just adds a `createSbot` function to the returned sbot object.

Adds way to create new sbots.

---

lib/detect-sync.js

hack as in i'm not 100% sure why but at least my sbot doesn't crash
see ssbc/scuttlebot#484

hack: don't use null messages

---

README.md

Updated Readme to add license and fix #474

Updated Readme to add license

---

api.md
index.js
lib/validators.js

this call was removed in secure-scuttlebutt v18.
fixes #518

relatedMessages: remove leftovers

---

package.json

Patchbay has been using this for at least a week and it appears stable for people.

Bump ssb-friends to 3.1.3

---

index.js

This PR is to add support for [multiple identities](https://github.com/ssbc/ssb-identities) managed by a single sbot. Also [see the discussion here](https://github.com/ssbc/secure-scuttlebutt/pull/213) for some more context.

Add multiple identity (ssb-identities) support for unboxing

---

test/bin.js

I simplified the test code and fixed at least one bug in it. This could heal travis.

Bugfix and cleanup in test/bin.js

---

README.md

Old link was dead.
Resolves #588

Update readme to use new Scuttlebutt link

---

test/bin.js

I originally pushed this to #566 but I think this should likely be in its own PR so I cherry-picked it. As long as Travis passes this should be good to merge.
---
Resolves #586

Specify "SIGKILL" to pass Travis tests

---

package.json
plugins/gossip/index.js

Hey I think this fixes the problems we've been having.
should fix https://github.com/ssbc/scuttlebot/issues/579
main fix was https://github.com/ssbc/ssb-ref/pull/30 which allows sbot to rebuild the peers list from pub messages. @christianbundy @mmckegg @arj03 @mixmix does this fix problems you were seeing?

some fixes to gossip for v13

---

test/invite.js

I think this should get things passing for you @mixmix can you run the tests on this branch?

fix invite tests when device has public ipv6 address

---

npm-shrinkwrap.json
package.json
scripts/pretest.js

Resolves #631 
I'm going to quickly merge this because it's trivial and currently tests on master are failing because of #624 again, please ping me if it causes any trouble.

Fix pretest by checking against ssb-server devDeps

---

npm-shrinkwrap.json
package.json

I didn't spend any time debugging the problem, this is just the result of `npm run reinstall`.
Resolves https://github.com/ssbc/ssb-server/issues/641

Fix shrinkwrap file

---

npm-shrinkwrap.json
package.json

It looks like the command-line flag is haunted and causing problems (resolves #654) but this seems to work?

Fix rebuild command with environment variable

---

README.md
bin.js

See https://github.com/ssbc/ssb-server/commit/f55b0b705d2b4ca3333d7321bdb5795a746e226a for discussion

Restore ssb-links and link to ssb-minimal-pub-server

---

npm-shrinkwrap.json
package.json

This includes the recent flumedb changes that allow support for deleted messages in the flumelog.
The only bummer here is that ssb-ws is still broken in Patchwork and Patchbay: https://github.com/ssbc/ssb-ws/issues/19

Upgrade npm dependencies

---

npm-shrinkwrap.json

Fixes lots of `npm audit` dependency issues.
See: #686

Run `npm audit fix`

---

plugins/blobs.html
plugins/block.html
plugins/friends.html
plugins/gossip.html
plugins/private.html
plugins/replicate.html

The docs site has has broken links since Christian renamed it to ssb-server and it's been driving me crazy so i fixed it.

Fixes broken links in the docs

---

README.md

Fix kappa architecture link

---

test/bin.js

@regular this fixes the weird behaviour I was getting with the bin test: https://github.com/ssbc/scuttlebot/issues/565
In the process of trying to understand the test, I also simplified it a bit. Now it just iterates through the various combinations of config file, cli opts, connecting to ws or net, for different hosts.
Although, I notice it doesn't actually cover the problem I was having, because most of the tests do not run the cli client, just check that a network connection can be made to sbot.
@regular on that note, did you see: https://github.com/ssbc/ssb-integration-tests

Fix bin test

---

index.js
lib/progress.js
test/bin.js
test/caps.js
test/multiple-sbots.js

I want to make code more accessible.
For me, I find I trip a lot on variables that aren't used - they take my attention away from what's important.
I think I might move through some of the core modules and remove or comment out variables which are not being used.
The intent of this is to make it more easy for more people to contribute to maintenance and growth <3

remove variables that are not used

---

README.md

This change would provide a great deal of simplicity when someone tries to make a new pub server.  A user by following these steps will create a pub server quickly and will circumvent a lot of the errors which I ran into.

A user-friendly update to Readme.md

---

bin.js
package-lock.json
package.json

Update ssb-client to 4.5.0 and removes the blobs.add hack (which is part of ssb-client since ssb-client@4.5.0)

Remove hack and fix blobs.add on cli

---

npm-shrinkwrap.json
package.json

Fix crash as mentioned in https://github.com/ssbc/ssb-server/issues/737#issuecomment-718250217

Bump ssb-links

---

README.md

Context:
- https://gist.github.com/shadowcat-mst/998cea12794768bdb3da2daeff31baad
- [%YFVcX0uL5Q8cfJyqUPTPQV7M/F3SA1nneUmva90JFO0=.sha256](https://viewer.scuttlebot.io/%25YFVcX0uL5Q8cfJyqUPTPQV7M%2FF3SA1nneUmva90JFO0%3D.sha256)
Also:
- https://github.com/ssbc/ssb-first-aid-kit/pull/37
- [scuttlebot.io %Ne19eRe…](https://git.scuttlebot.io/%25Ne19eReNlhXTztYgU%2By1GP2pCGiPmbyJkqfI2YS0s98%3D.sha256)

Change IRC network to Libera Chat
